-- AEGIS v3.2 SaTML 2027 — Anonymous Artifact
-- 01_schema_and_tables.sql
-- Creates the evaluation schema and all required tables.
-- Namespace: ARTIFACT_DB.AEGIS_REPRO

CREATE DATABASE IF NOT EXISTS ARTIFACT_DB;
CREATE SCHEMA IF NOT EXISTS ARTIFACT_DB.AEGIS_REPRO;
USE SCHEMA ARTIFACT_DB.AEGIS_REPRO;

CREATE OR REPLACE TABLE AEGIS_THREAT_ATTRIBUTE (
    THREAT_ATTRIBUTE_ID VARCHAR(10) NOT NULL,
    THREAT_CATEGORY VARCHAR(50) NOT NULL,
    THREAT_NAME VARCHAR(200) NOT NULL,
    ADVERSARIAL_INTENT_CLASS VARCHAR(50),
    INSTRUCTION_MANIPULATION_CLASS VARCHAR(50),
    RETRIEVAL_MANIPULATION_CLASS VARCHAR(50),
    PAYLOAD_TRUST_CLASS VARCHAR(50),
    RETRIEVAL_RISK_TYPE VARCHAR(50),
    SEVERITY_WEIGHT NUMBER(10,4) NOT NULL,
    EXPECTED_DECISION VARCHAR(10) NOT NULL,
    DETECTION_METHOD VARCHAR(50) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE AEGIS_TEST_CASE (
    TEST_ID VARCHAR(20) NOT NULL,
    TEST_FAMILY VARCHAR(100) NOT NULL,
    PURPOSE_SUMMARY VARCHAR(500),
    REQUEST_PAYLOAD VARCHAR(4000),
    EXPECTED_DECISION VARCHAR(10) NOT NULL,
    EXPECTED_ADVERSARIAL_INTENT_CLASS VARCHAR(50),
    EXPECTED_INSTRUCTION_MANIPULATION_CLASS VARCHAR(50),
    EXPECTED_RETRIEVAL_MANIPULATION_CLASS VARCHAR(50),
    EXPECTED_PAYLOAD_TRUST_CLASS VARCHAR(50),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE AEGIS_DECISION_LOG (
    DECISION_ID VARCHAR(36) NOT NULL,
    REQUEST_ID VARCHAR(36),
    TEST_ID VARCHAR(20),
    PARSE_SNAPSHOT VARIANT,
    POLICY_RESOLUTION_RESULT VARIANT,
    RESTRICTION_ENVELOPE VARIANT,
    RETRIEVAL_RISK_JSON VARIANT,
    MATCHED_THREAT_ATTRIBUTES VARIANT,
    RETRIEVAL_RISK_SCORE NUMBER(10,4),
    RISK_CLASS VARCHAR(10),
    AUTHORIZATION_DECISION VARCHAR(10),
    DECISION_REASON VARCHAR(500),
    ENFORCEMENT_ACTION VARCHAR(50),
    CONTEXT_ASSEMBLY_STATUS VARCHAR(50),
    LATENCY_MS NUMBER(18,3),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AEGIS_COMPARATIVE_BENCHMARK_690 (
    BENCHMARK_LABEL VARCHAR(100),
    CONDITION_NAME VARCHAR(50),
    TOTAL_TESTS NUMBER,
    BLOCK_DECISIONS NUMBER,
    RESTRICT_DECISIONS NUMBER,
    PERMIT_DECISIONS NUMBER,
    HOSTILE_TESTS NUMBER,
    HOSTILE_BLOCKED NUMBER,
    HOSTILE_PERMITTED NUMBER,
    BENIGN_TESTS NUMBER,
    BENIGN_PERMITTED NUMBER,
    BENIGN_BLOCKED NUMBER,
    ASR NUMBER(10,4),
    CPR NUMBER(10,4),
    FPR NUMBER(10,4),
    RPR NUMBER(10,4),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AEGIS_EVALUATION_GOVERNANCE (
    SNAPSHOT_ID VARCHAR(36),
    SNAPSHOT_LABEL VARCHAR(100),
    TA_VERSION VARCHAR(50),
    TA_COUNT NUMBER,
    TA_HASH VARCHAR(64),
    CORPUS_VERSION VARCHAR(50),
    CORPUS_COUNT NUMBER,
    CORPUS_HASH VARCHAR(64),
    ONTOLOGY_INTENT_VALUES VARIANT,
    ONTOLOGY_INSTRUCTION_VALUES VARIANT,
    ONTOLOGY_RETRIEVAL_VALUES VARIANT,
    ONTOLOGY_PAYLOAD_VALUES VARIANT,
    SCORING_THRESHOLD_RESTRICT NUMBER(10,4),
    SCORING_THRESHOLD_BLOCK NUMBER(10,4),
    MATCHING_LOGIC_VERSION VARCHAR(100),
    BENCHMARK_LABEL VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ONTOLOGY_ADVERSARIAL_INTENT_CLASS (
    ADVERSARIAL_INTENT_CLASS VARCHAR(50) NOT NULL
);

CREATE OR REPLACE TABLE ONTOLOGY_INSTRUCTION_MANIPULATION_CLASS (
    INSTRUCTION_MANIPULATION_CLASS VARCHAR(50) NOT NULL
);

CREATE OR REPLACE TABLE ONTOLOGY_RETRIEVAL_MANIPULATION_CLASS (
    RETRIEVAL_MANIPULATION_CLASS VARCHAR(50) NOT NULL
);

CREATE OR REPLACE TABLE ONTOLOGY_PAYLOAD_TRUST_CLASS (
    PAYLOAD_TRUST_CLASS VARCHAR(50) NOT NULL
);
