-- AEGIS v3.2 SaTML 2027 — Anonymous Artifact
-- 02_threat_attributes.sql
-- 15 governed threat attributes (frozen v3.2 state)

USE SCHEMA ARTIFACT_DB.AEGIS_REPRO;

INSERT INTO AEGIS_THREAT_ATTRIBUTE VALUES
('TA-001','AUTHORITY_OVERRIDE','Ignore prior controls','AUTHORITY_OVERRIDE','IGNORE_PRIOR',NULL,'HOSTILE_INSTRUCTION','INSTRUCTION_OVERRIDE',0.9500,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-002','POLICY_BYPASS','Bypass governance controls','POLICY_BYPASS','SYSTEM_OVERRIDE',NULL,'HOSTILE_INSTRUCTION','POLICY_BYPASS',0.9500,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-003','RETRIEVAL_REDIRECTION','Unauthorized retrieval redirect','RETRIEVAL_REDIRECTION',NULL,'UNAUTHORIZED_SOURCE','HOSTILE_INSTRUCTION','RETRIEVAL_PATH',0.9000,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-004','SCOPE_ESCALATION','Scope expansion','RETRIEVAL_REDIRECTION',NULL,'SCOPE_EXPANSION',NULL,'SCOPE_EXPANSION',0.7000,'RESTRICT','SEMANTIC_ATTRIBUTE',TRUE),
('TA-005','DATA_EXFILTRATION','Sensitive data retrieval','DATA_EXFILTRATION',NULL,'UNAUTHORIZED_SOURCE','HOSTILE_INSTRUCTION','SENSITIVE_RETRIEVAL',0.9800,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-006','WORKFLOW_MANIPULATION','Workflow sequence bypass','WORKFLOW_MANIPULATION','SYSTEM_OVERRIDE',NULL,'HOSTILE_INSTRUCTION','WORKFLOW_CONTROL',0.8500,'RESTRICT','SEMANTIC_ATTRIBUTE',TRUE),
('TA-007','OBFUSCATION','Encoded hostile payload','UNKNOWN','HIDDEN_INSTRUCTION',NULL,'OBFUSCATED','OBFUSCATION',0.7500,'RESTRICT','SEMANTIC_ATTRIBUTE',TRUE),
('TA-008','UNKNOWN_RISK','Unknown adversarial posture','UNKNOWN','UNKNOWN','UNKNOWN','UNKNOWN','UNKNOWN',0.6000,'RESTRICT','FAIL_CLOSED',TRUE),
('TA-009','RETRIEVAL_REDIRECTION','Cross-domain retrieval redirect','RETRIEVAL_REDIRECTION',NULL,'CROSS_DOMAIN_REDIRECT','USER_ASSERTED_AUTHORITY','RETRIEVAL_PATH',0.7000,'RESTRICT','SEMANTIC_ATTRIBUTE',TRUE),
('TA-010','ROLE_IMPERSONATION','Authority override via identity impersonation','AUTHORITY_OVERRIDE','ROLE_IMPERSONATION',NULL,NULL,'INSTRUCTION_OVERRIDE',0.9000,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-011','ROLE_IMPERSONATION','Policy bypass via identity impersonation','POLICY_BYPASS','ROLE_IMPERSONATION',NULL,NULL,'POLICY_BYPASS',0.9000,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-012','ROLE_IMPERSONATION','Data exfiltration via identity impersonation','DATA_EXFILTRATION','ROLE_IMPERSONATION',NULL,NULL,'SENSITIVE_RETRIEVAL',0.9000,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-017','CONCEALMENT','Concealed authority override','AUTHORITY_OVERRIDE','HIDDEN_INSTRUCTION',NULL,NULL,'INSTRUCTION_OVERRIDE',0.9000,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-018','CONCEALMENT','Concealed policy bypass','POLICY_BYPASS','HIDDEN_INSTRUCTION',NULL,NULL,'POLICY_BYPASS',0.9000,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE),
('TA-019','CONCEALMENT','Concealed data exfiltration','DATA_EXFILTRATION','HIDDEN_INSTRUCTION',NULL,NULL,'SENSITIVE_RETRIEVAL',0.9500,'BLOCK','SEMANTIC_ATTRIBUTE',TRUE);
