-- AEGIS v3.2 SaTML 2027 — Anonymous Artifact
-- 03_ontology_tables.sql
-- 4 ontology dimension tables (25 values across 4 semantic dimensions)

USE SCHEMA ARTIFACT_DB.AEGIS_REPRO;

INSERT INTO ONTOLOGY_ADVERSARIAL_INTENT_CLASS VALUES
('AUTHORITY_OVERRIDE'),('DATA_EXFILTRATION'),('NONE'),('POLICY_BYPASS'),
('RETRIEVAL_REDIRECTION'),('UNKNOWN'),('WORKFLOW_MANIPULATION');

INSERT INTO ONTOLOGY_INSTRUCTION_MANIPULATION_CLASS VALUES
('HIDDEN_INSTRUCTION'),('IGNORE_PRIOR'),('NONE'),('ROLE_IMPERSONATION'),
('SYSTEM_OVERRIDE'),('UNKNOWN');

INSERT INTO ONTOLOGY_RETRIEVAL_MANIPULATION_CLASS VALUES
('CROSS_DOMAIN_REDIRECT'),('NONE'),('SCOPE_EXPANSION'),
('TOOL_PARAMETER_MANIPULATION'),('UNAUTHORIZED_SOURCE'),('UNKNOWN');

INSERT INTO ONTOLOGY_PAYLOAD_TRUST_CLASS VALUES
('BENIGN_SECURITY_DISCUSSION'),('HOSTILE_INSTRUCTION'),('NORMAL'),
('OBFUSCATED'),('UNKNOWN'),('USER_ASSERTED_AUTHORITY');
